version: '3.9'

services:
  frontend:
    build:
      context: .
    container_name: banister_frontend
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:8000
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    command: npm run dev
    stdin_open: true
    tty: true